### ISSUE TITLE
sphinx-rtd-theme should be a dev-dependency

### ISSUE THREAD

**Issue by SamEdwardes** [SamEdwardes/pydatafaker#8]
To make readthedocs work I had to make `sphinx-rtd-theme` a dependency. 

https://github.com/SamEdwardes/pydatafaker/blob/74aa03d72453bffb9d510dc54e9849aa3acd8d5b/pyproject.toml#L12

It is not actually required, but for some reason the docs did not build when I moved it to:

```
[tool.poetry.dev-dependencies]
sphinx-rtd-theme = "^0.5.0" 
```

It would be ideal to find a way to make the docs build with `sphinx-rtd-theme = "^0.5.0" ` in `[tool.poetry.dev-dependencies]`.

[Error message](https://readthedocs.org/projects/pydatafaker/builds/11808287/) from readthedocs:

```
Running Sphinx v1.8.5
loading translations [en]... done
making output directory...
[autosummary] generating autosummary for: api_reference.rst, contributing.rst, index.rst, usage.rst
[autosummary] generating autosummary for: /home/docs/checkouts/readthedocs.org/user_builds/pydatafaker/checkouts/business_and_docs/docs/source/generated/pydatafaker.business.create_business.rst, /home/docs/checkouts/readthedocs.org/user_builds/pydatafaker/checkouts/business_and_docs/docs/source/generated/pydatafaker.business.create_employee_table.rst, /home/docs/checkouts/readthedocs.org/user_builds/pydatafaker/checkouts/business_and_docs/docs/source/generated/pydatafaker.business.create_invoice_table.rst, /home/docs/checkouts/readthedocs.org/user_builds/pydatafaker/checkouts/business_and_docs/docs/source/generated/pydatafaker.business.create_po_table.rst, /home/docs/checkouts/readthedocs.org/user_builds/pydatafaker/checkouts/business_and_docs/docs/source/generated/pydatafaker.business.create_vendor_table.rst, /home/docs/checkouts/readthedocs.org/user_builds/pydatafaker/checkouts/business_and_docs/docs/source/generated/pydatafaker.business.rst
building [mo]: targets for 0 po files that are out of date
building [readthedocs]: targets for 4 source files that are out of date
updating environment: 10 added, 0 changed, 0 removed
reading sources... [ 10%] api_reference
reading sources... [ 20%] contributing
reading sources... [ 30%] generated/pydatafaker.business
reading sources... [ 40%] generated/pydatafaker.business.create_business
reading sources... [ 50%] generated/pydatafaker.business.create_employee_table
reading sources... [ 60%] generated/pydatafaker.business.create_invoice_table
reading sources... [ 70%] generated/pydatafaker.business.create_po_table
reading sources... [ 80%] generated/pydatafaker.business.create_vendor_table
reading sources... [ 90%] index
reading sources... [100%] usage


Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pydatafaker/envs/business_and_docs/lib/python3.7/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pydatafaker/envs/business_and_docs/lib/python3.7/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pydatafaker/envs/business_and_docs/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/pydatafaker/envs/business_and_docs/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 360, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/pydatafaker/envs/business_and_docs/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 472, in read
    self.env.doc2path(self.config.master_doc))
sphinx.errors.SphinxError: master file /home/docs/checkouts/readthedocs.org/user_builds/pydatafaker/checkouts/business_and_docs/docs/source/contents.rst not found

Sphinx error:
master file /home/docs/checkouts/readthedocs.org/user_builds/pydatafaker/checkouts/business_and_docs/docs/source/contents.rst not found

```

**Comment by SamEdwardes** [comment]
Hey @TomasBeuzen, I am sure you are super busy with school starting... but wondering if you had any ideas on fixes? I am developing this Python package using poetry. I am trying to publish to readthedocs.

When I include my desired sphinx theme as a dependency the build works. But this is not desired, as when the user pip installs the package it downloads packages that are not really required.

```toml
# pyproject.toml
[tool.poetry.dependencies]
python = "^3.7"
pandas = "^1.1.1"
faker = "^4.1.2"
sphinx-rtd-theme = "^0.5.0" # should be a dev requirement, but for readthedocs to build must by a dependency
```

When I set up correctly, for some reason the [build fails](https://readthedocs.org/projects/pydatafaker/builds/11808287/) (not sure if this link will work for you, but it is too failed build.

```toml
[tool.poetry.dependencies]
python = "^3.7"
pandas = "^1.1.1"
faker = "^4.1.2"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"
black = {version = "^20.8b1", allow-prereleases = true}
sphinx = "^3.2.1"
sphinxcontrib-napoleon = "^0.7"
sphinx-rtd-theme = "^0.5.0" # should be a dev requirement, but for readthedocs to build must by a dependency
pytest-cov = "^2.10.1"
```

I have the .`readthedocs.yml` from your [cookiecutter project](https://github.com/UBC-MDS/cookiecutter-ubc-mds/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/.readthedocs.yml), but it doesn't seem to do the  trick.

```yml
# .readthedocs.yml
# https://github.com/UBC-MDS/cookiecutter-ubc-mds/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/.readthedocs.yml

build:
    image: latest
python:
    version: 3.7
    pip_install: true
    extra_requirements:
        - docs
```

Similar issues on GitHub include: 

- https://github.com/python-poetry/poetry/issues/754
- https://github.com/readthedocs/readthedocs.org/issues/4912?source=post_page---------------------------
- https://github.com/readthedocs/readthedocs.org/issues/6151
